"""Initial migration.

Revision ID: 38112d413f88
Revises: 
Create Date: 2023-11-25 01:50:06.802936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38112d413f88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
